### ISSUE TITLE
not work in IE 11

### ISSUE THREAD

**Issue by paranoid945** [IguMail/socketio-shared-webworker#2]

**Comment by fijiwebdesign** [comment]
Yes, shared webworkers is not available in IE and Safari. Only Chrome, Firefox and Opera. 
http://caniuse.com/#search=shared%20web%20worker

I will add a conditional test and load original socket.io when webworkers is not supported.

**Comment by StefansArya** [comment]
How about using [intercom.js](https://github.com/diy/intercom.js) as a fallback when shared webworkers was not available?

**Comment by tony-gutierrez** [comment]
Does this only use shared webworkers? It cant be written to use a dedicated?

**Comment by fijiwebdesign** [comment]
With version `^1.1.0` you can use a `Worker` using:

```
ws.setWorkerType(Worker)
```

It will fallback to regular `socket.io` if `Worker` or `SharedWorker` is not supported.
